[versions]
kotlin = "2.2.21"
compose-plugin = "1.9.2"
filekit = "0.12.0"
ksp = "2.3.1"
slf4j = "2.0.17"
xml-builder = "1.9.3"
autoservice-ksp = "1.2.0"
autoservice = "1.1.1"
open = "8.5.0.4"
composeHotReload = "1.0.0-rc02"

[libraries]
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
kotlin-xml-builder = { module = "org.redundent:kotlin-xml-builder", version.ref = "xml-builder" }
auto-service-ksp = { module = "dev.zacsweers.autoservice:auto-service-ksp", version.ref = "autoservice-ksp" }
auto-service-annotations = { module = "com.google.auto.service:auto-service-annotations", version.ref = "autoservice" }
open = { module = "com.vaadin:open", version.ref = "open" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload"}
